// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcecWlv5v3Kf6Fjfef_LIKEEr4mZIRg7k',
    appId: '1:186250972527:web:19a33237b210c76776ec9a',
    messagingSenderId: '186250972527',
    projectId: 'flutter-notification-pra-41809',
    authDomain: 'flutter-notification-pra-41809.firebaseapp.com',
    storageBucket: 'flutter-notification-pra-41809.firebasestorage.app',
    measurementId: 'G-XZZH532ZLV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrjn7DfjLn4buWNBMorHxtZreRUkhgVqI',
    appId: '1:186250972527:android:1adce07e0a54bf9f76ec9a',
    messagingSenderId: '186250972527',
    projectId: 'flutter-notification-pra-41809',
    storageBucket: 'flutter-notification-pra-41809.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHY5oHBbzpi79R9pRCdXjPkH8w7AkD98E',
    appId: '1:186250972527:ios:1a05467259bf292576ec9a',
    messagingSenderId: '186250972527',
    projectId: 'flutter-notification-pra-41809',
    storageBucket: 'flutter-notification-pra-41809.firebasestorage.app',
    iosBundleId: 'com.technicalencoder.flutterNotifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHY5oHBbzpi79R9pRCdXjPkH8w7AkD98E',
    appId: '1:186250972527:ios:b042a3b5ff0df61676ec9a',
    messagingSenderId: '186250972527',
    projectId: 'flutter-notification-pra-41809',
    storageBucket: 'flutter-notification-pra-41809.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNotificationPractice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcecWlv5v3Kf6Fjfef_LIKEEr4mZIRg7k',
    appId: '1:186250972527:web:d6eec4ddf4e32f0276ec9a',
    messagingSenderId: '186250972527',
    projectId: 'flutter-notification-pra-41809',
    authDomain: 'flutter-notification-pra-41809.firebaseapp.com',
    storageBucket: 'flutter-notification-pra-41809.firebasestorage.app',
    measurementId: 'G-C50664Q36Z',
  );
}
